exports.constants = {
  VALIDATION_ERROR: 400,
  NOT_FOUND: 404,
  FORBIDDEN: 403,
  UNAUTHORIZED: 401,
  SERVER_ERROR: 500,
};

exports.TYPES = {
  POST_LIKE: "P",
  COMMENT_LIKE: "C",
  REPLY_LIKE: "R",
};
